# Copyright (C) 2018 BROADSoftware
#
# This file is part oEzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.

type: map
mapping:
  "repositories":
    type: map
    required: false
    mapping:
      "vagrant":
        type: map
        required: false
        mapping:
          "yum_repo_base_url": { type: str, required: false }
  "boxes":
    type: seq
    required: false
    sequence:
      - type: map
        mapping:
          "names":
            type: seq
            sequence:
              - type: str
          "os_family": { type: str, required: true, enum: [ "RedHat", "Debian" ] }   # Refer to os_family ansible variable
          "storageController": { type: str, required: true }
          "firstFreeDiskPort": { type: int, required: true }
          "defaultFsType": { type: str, required: true }

    
    
    
  
