

# Copyright (C) 2022 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


schema;node_list:
  type: seq
  required: false
  sequence:
  - type: map
    mapping:
      "openstack":
        type: map
        required: false
        mapping:
          "network": { type: str, required: false }
          "availability_zone": { type: str, required: false }



type: map
mapping:
  openstack:
    type: map
    required: true
    mapping:
      "project": { type: str, required: true }
      "defaults":
        type: map
        required: false
        mapping:
          "image": { type: str, required: false }
          "flavor": { type: str, required: false }
          "security_groups": { type: seq, required: false, sequence: [{ type: str }] }
          "network": { type: str, required: false }
          "availability_zone": { type: str, required: false }
          "data_fstype": { type: str, required: false }
      "image_default": { type: str, required: false }
      "network_default": { type: str, required: false }
      "flavor_default": { type: str, required: false }
      "az_default": { type: str, required: false }
      "security_group_default": { type: str, required: false }
      "security_groups":
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              "name": { type: str, required: true }
              "description": { type: str, required: false }
              "outbound_rules":
                type: seq
                required: false
                sequence:
                  - type: map
                    mapping:
                      "description": { type: str, required: false }
                      "protocol": { type: str, required: true, enum: [ "all", "tcp", "udp", "icmp", "ah", "dccp", "egp", "esp", "gre", "igmp", "ospf", "pgm", "rsvp", "sctp", "udplite", "vrrp" ] }
                      "from_port": { type: int, required: false }
                      "to_port": { type: int, required: false }
                      "port": { type: str, required: false }
                      "icmp_type": { type: int, required: false }
                      "icmp_code": { type: int, required: false }
                      "remote_cidr": { type: str, required: false }
                      "remote_sg": { type: str, required: false }
              "inbound_rules":
                type: seq
                required: false
                sequence:
                  - type: map
                    mapping:
                      "description": { type: str, required: false }
                      "protocol": { type: str, required: true, enum: [ "all", "tcp", "udp", "icmp", "ah", "dccp", "egp", "esp", "gre", "igmp", "ospf", "pgm", "rsvp", "sctp", "udplite", "vrrp" ] }
                      "from_port": { type: int, required: false }
                      "to_port": { type: int, required: false }
                      "port": { type: str, required: false }
                      "icmp_type": { type: int, required: false }
                      "icmp_code": { type: int, required: false }
                      "remote_cidr": { type: str, required: false }
                      "remote_sg": { type: str, required: false }
      "flavors":
        type: seq
        required: false
        sequence:
          - type: map
            mapping:
              "name": { type: str, required: true }
              "description": { type: str, required: false }
              "ram_mb": { type: int, required: true }
              "vcpus": { type: int, required: true }
              "disk_gb": { type: int, required: true }


  roles:
    type: seq
    required: true
    sequence:
      - type: map
        mapping:
          "swap_size_gb": { type: int, required: true }
          "openstack":
            type: map
            required: false
            mapping:
              "image": { type: str, required: false }
              "flavor": { type: str, required: false }
              "security_groups":
                type: seq
                required: false
                sequence:
                  - type: str
          "data_disks":
            type: seq
            required: false
            sequence:
            - type: map
              mapping:
                "size": { type: int, required: true }
                "device": { type: str, required: false }    # Normaly, computed by the system. Just in case we need to overwrite
                "mount": { type: str, required: false }
                "fstype": { type: str, required: false }
